apiVersion: v1
kind: Service
metadata:
  name: pragna-api-external
  namespace: pragna-staging
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  type: ExternalName
  externalName: api-staging.sgummallaworks.com
  ports:
    - port: 443
      targetPort: 443
