"""
LLM Provider Registry — metadata + async model-list fetchers for all supported providers.

fetch_models() returns list[{"model_id": str, "display_name": str}].
Display names are generated by _prettify() — no hardcoded lookup tables.
"""

from __future__ import annotations

import asyncio
import logging

logger = logging.getLogger(__name__)

PROVIDER_ORDER = ["anthropic", "openai", "google", "perplexity", "groq"]

PROVIDERS: dict[str, dict] = {
    "anthropic": {
        "name":        "Anthropic",
        "description": "Claude Opus, Sonnet, Haiku",
        "placeholder": "sk-ant-api03-…",
        "key_label":   "Anthropic API Key",
        "auth_modes": [
            {
                "id":    "direct",
                "label": "Direct API",
                "fields": [
                    {"key": "anthropic", "label": "API Key", "placeholder": "sk-ant-api03-…"},
                ],
            },
            {
                "id":    "bedrock",
                "label": "AWS Bedrock",
                "fields": [
                    {"key": "anthropic_bedrock_url",   "label": "Bedrock Base URL", "placeholder": "https://…"},
                    {"key": "anthropic_bedrock_token", "label": "Auth Token",       "placeholder": "…"},
                ],
            },
        ],
    },
    "openai": {
        "name":        "OpenAI",
        "description": "GPT-4o, o3, o4-mini and more",
        "placeholder": "sk-proj-…",
        "key_label":   "OpenAI API Key",
    },
    "google": {
        "name":        "Google",
        "description": "Gemini models",
        "placeholder": "AIza…",
        "key_label":   "Google API Key",
    },
    "perplexity": {
        "name":        "Perplexity",
        "description": "Sonar search-grounded models",
        "placeholder": "pplx-…",
        "key_label":   "Perplexity API Key",
    },
    "groq": {
        "name":        "Groq",
        "description": "Fast inference — Llama, Mixtral, Gemma",
        "placeholder": "gsk_…",
        "key_label":   "Groq API Key",
    },
}

# OpenAI non-chat model prefixes to exclude
_OPENAI_EXCLUDE_PREFIXES = (
    "text-embedding", "tts-", "whisper-", "dall-e", "davinci", "babbage",
    "text-moderation", "gpt-3.5-turbo-instruct", "ft:", "o1-mini-2024",
)


def _prettify(model_id: str) -> str:
    """
    Convert a raw model ID into a human-readable display name.
    No lookup tables — works for any model ID.

    Examples:
      claude-sonnet-4-6          → Claude Sonnet 4.6
      gpt-4o-mini                → GPT-4o Mini
      llama-3.3-70b-versatile    → Llama 3.3 70b Versatile
      gemini-1.5-pro             → Gemini 1.5 Pro
      sonar-pro                  → Sonar Pro
    """
    _ALWAYS_UPPER = {"gpt", "aws", "llm", "api", "sdk"}

    # Normalise: dots in version numbers, strip vendor prefixes like us.anthropic.
    mid = model_id
    if "." in mid and mid.count(".") > 1:
        # e.g. us.anthropic.claude-sonnet-4-6 → claude-sonnet-4-6
        mid = mid.split(".")[-1]

    # Replace underscores then split on hyphens
    parts = mid.replace("_", "-").split("-")
    words = []
    for p in parts:
        if not p:
            continue
        low = p.lower()
        if low in _ALWAYS_UPPER:
            words.append(p.upper())
        else:
            words.append(p[0].upper() + p[1:])

    return " ".join(words)


def _model_entry(model_id: str) -> dict:
    return {"model_id": model_id, "display_name": _prettify(model_id)}


async def fetch_models(
    provider_id:   str,
    api_key:       str,
    mode:          str = "direct",
    bedrock_url:   str = "",
    bedrock_token: str = "",
    catalog_models: list[dict] | None = None,
) -> list[dict]:
    """
    Fetch available models for the given provider.
    Returns list[{"model_id": str, "display_name": str}], sorted by model_id.

    catalog_models — required for providers without a model listing API
    (bedrock, perplexity). Pass rows from db.model_catalog.get_by_provider().
    Raises on auth failure or network error.
    """
    if provider_id == "anthropic":
        return await _fetch_anthropic(api_key, mode=mode,
                                      bedrock_url=bedrock_url,
                                      bedrock_token=bedrock_token,
                                      catalog_models=catalog_models or [])

    if provider_id == "perplexity":
        return await _fetch_perplexity(api_key, catalog_models=catalog_models or [])

    fetchers = {
        "openai": _fetch_openai,
        "google": _fetch_google,
        "groq":   _fetch_groq,
    }
    fn = fetchers.get(provider_id)
    if fn is None:
        raise ValueError(f"Unknown provider: {provider_id!r}")
    return await fn(api_key)


# ── Per-provider fetchers ─────────────────────────────────────────────────────

async def _fetch_anthropic(
    api_key:        str,
    mode:           str = "direct",
    bedrock_url:    str = "",
    bedrock_token:  str = "",
    catalog_models: list[dict] | None = None,
) -> list[dict]:
    import anthropic
    if mode == "bedrock":
        if not catalog_models:
            raise ValueError("No Bedrock models found in catalog. Add them via Settings → Providers.")
        client = anthropic.AsyncAnthropicBedrock(
            base_url=bedrock_url,
            api_key=bedrock_token,
        )
        # Validate connectivity using the first catalog model
        await client.messages.create(
            model=catalog_models[0]["model_id"],
            max_tokens=1,
            messages=[{"role": "user", "content": "hi"}],
        )
        return sorted(catalog_models, key=lambda x: x["model_id"])
    else:
        client   = anthropic.AsyncAnthropic(api_key=api_key)
        response = await client.models.list(limit=100)
        return sorted([_model_entry(m.id) for m in response.data], key=lambda x: x["model_id"])


async def _fetch_openai(api_key: str) -> list[dict]:
    import openai
    client   = openai.AsyncOpenAI(api_key=api_key)
    response = await client.models.list()
    ids = [
        m.id for m in response.data
        if not any(m.id.startswith(p) for p in _OPENAI_EXCLUDE_PREFIXES)
    ]
    return sorted([_model_entry(m) for m in ids], key=lambda x: x["model_id"])


async def _fetch_google(api_key: str) -> list[dict]:
    import google.generativeai as genai
    genai.configure(api_key=api_key)
    loop = asyncio.get_event_loop()

    def _list():
        return [
            m.name.removeprefix("models/")
            for m in genai.list_models()
            if "generateContent" in (m.supported_generation_methods or [])
        ]

    ids = await loop.run_in_executor(None, _list)
    return sorted([_model_entry(m) for m in ids], key=lambda x: x["model_id"])


async def _fetch_perplexity(api_key: str, catalog_models: list[dict] | None = None) -> list[dict]:
    if not api_key.startswith("pplx-"):
        raise ValueError("Perplexity API keys begin with 'pplx-'. Please check your key.")
    if not catalog_models:
        raise ValueError("No Perplexity models found in catalog. Add them via Settings → Providers.")
    return catalog_models


async def _fetch_groq(api_key: str) -> list[dict]:
    import openai
    client   = openai.AsyncOpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")
    response = await client.models.list()
    return sorted([_model_entry(m.id) for m in response.data], key=lambda x: x["model_id"])
