apiVersion: apps/v1
kind: Deployment
metadata:
  name: pragna-api
  namespace: pragna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pragna-api
  template:
    metadata:
      labels:
        app: pragna-api
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: pragna-api
          image: ghcr.io/sgummalla79/pragna-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: pragna-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10